### ISSUE TITLE
The provider configuration to add to clusterctl.yaml is wrong

### ISSUE THREAD

**Issue by agtogna** [kubernetes-sigs/cluster-api-ipam-provider-in-cluster#169]
The provider URL is no longer on telekom but has moved to kubernetes-sigs, so should be:

```
providers:
  - name: in-cluster
    url: https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/releases/latest/ipam-components.yaml
    type: IPAMProvider
```

otherwise clusterctl init errors with:

```
Fetching providers
Error: failed to get provider components for the "in-cluster" provider: target namespace can't be defaulted. Please specify a target namespace
```
