### ISSUE TITLE
clusterctl init fails if wrong version of cert-manager is already installed

### ISSUE THREAD

**Issue by agtogna** [kubernetes-sigs/cluster-api-ipam-provider-in-cluster#211]
**If cert-manager is already installed in the ClusterAPI management cluster (before it is initialized) but is not the version expected by clusterctl**, then `clusterctl --ipam incluster --config clusterctl-IPAM.config.yaml`, with clusterctl-IPAM.config.yaml being:
```
---
providers:
  - name: incluster
    url: https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/releases/latest/ipam-components.yaml
    type: IPAMProvider
```
fails with a strange error:
```
Error: failed to get provider components for the "incluster" provider: failed to read "ipam-components.yaml" from provider's repository "ipam-incluster": release not found for version download, 
please retry later or set "GOPROXY=off" to get the current stable release: 404 Not Found
```

If I specify an IPAM version, e.g. v0.1.0-alpha.2 (`clusterctl init --ipam incluster:v0.1.0-alpha.2 --config clusterctl-IPAM.config.yaml`) the error is:
```
Error: failed to get provider components for the "incluster:v0.1.0-alpha.2" provider: failed to read "ipam-components.yaml" from provider's repository "ipam-incluster": failed to download files 
from GitHub release v0.1.0-alpha.2: failed to get file "ipam-components.yaml" from "v0.1.0-alpha.2" release 
```
