### ISSUE TITLE
unknown field "spec.excludedAddresses"

### ISSUE THREAD

**Issue by simonfelding** [kubernetes-sigs/cluster-api-ipam-provider-in-cluster#213]
Hi. Awesome sig!
There seems to be a bug in ipam.cluster.x-k8s.io/v1alpha2 that is poorly documented.
It is no longer spec.exclude, now it's apparently spec.excludedAddresses that defines the excluded addresses.

However, neither of them work now.
I'm using the following configuration.

```
apiVersion: ipam.cluster.x-k8s.io/v1alpha2
kind: InClusterIPPool
metadata:
  name: ${CLUSTER_CLASS_NAME}
  namespace: ${NAMESPACE}
spec:
  prefix: 25
  addresses:
    - 10.1.157.0/25
  excludedAddresses:
    - 10.1.157.1-10.1.157.20
  gateway: 10.1.157.1
```

The full error:
```
Error from server (BadRequest): error when creating "STDIN": InClusterIPPool in version "v1alpha2" cannot be handled as a InClusterIPPool: strict decoding error: unknown field "spec.excludedAddresses"
```
