### ISSUE TITLE
Cannot perform `clusterctl upgrade [apply|plan]` anymore after publication of `v1.0.0-rc.0`

### ISSUE THREAD

**Issue by gtriggiano** [kubernetes-sigs/cluster-api-ipam-provider-in-cluster#286]
When I launch either `clusterctl upgrade plan` or `clusterctl upgrade apply ...` i get this error:

```
Error: invalid provider metadata: version v1.0.0-rc.0 (one of the available versions) for the provider capi-ipam-in-cluster-system/ipam-incluster does not match any release series
```

I guess this error is caused by the name of the release tag

**Comment by mcbenjemaa** [comment]
Please stick to the old release until `v1.0.0` is released.

```
clusterctl upgrade apply --ipam v0.1.0
```

/kind support

**Comment by gtriggiano** [comment]
@mcbenjemaa thx for your reply.

I guess the right command would be
```
clusterctl upgrade apply --ipam capi-ipam-in-cluster-system/incluster:0.1.0
```

However the outcome does not change:
```
Performing upgrade...
Error: invalid provider metadata: version v1.0.0-rc.0 (one of the available versions) for the provider capi-ipam-in-cluster-system/ipam-incluster does not match any release series
```

I haven't had time to inspect the code thoroughly, but I believe the error is produced [here](https://github.com/kubernetes-sigs/cluster-api/blob/release-1.8/cmd/clusterctl/client/cluster/upgrader_info.go#L95-L97).

**Comment by gtriggiano** [comment]
Maybe the `metadata.yaml` should be updated to:
```
apiVersion: clusterctl.cluster.x-k8s.io/v1alpha3
kind: Metadata
releaseSeries:
  - major: 1
    minor: 0
    contract: v1beta1
  - major: 0
    minor: 1
    contract: v1beta1
```
?
